---
default_backend_url: http://www.google.com:80
port: 3000
db:
  database: "mysql://pivotal:@/test?charset=utf8&parseTime=True"
app_packages:
  provider: "local"
  filepath: "/tmp/api/app_packages"
  # Following are for S3 blobstore
  # provider: "s3"
  # access_key_id: "key_id"
  # access_key_secret: "key secret"
  # host: "s3.amazonaws.com"
  # bucket_name: "bucket_name"
