#!/bin/bash
set -e
(
export GOPATH=$PWD/Godeps/_workspace:$GOPATH
echo "Building..."
go install github.com/pivotal-cf-experimental/godep

./scripts/build
echo "Formating..."
go fmt ./...
echo "Vetting..."
go vet ./...
echo "Testing..."
ginkgo -r -randomizeAllSpecs -nodes=4 $@
echo "SUITE SUCCESS"
)

