#!/bin/bash
set -e
(
export GOPATH=$PWD/Godeps/_workspace:$GOPATH
echo "Building..."
./scripts/build

echo "Formating..."
go fmt ./...

echo "Vetting..."
go get code.google.com/p/go.tools/cmd/vet
go vet ./...
echo "Testing..."

go install github.com/onsi/ginkgo
ginkgo -r -randomizeAllSpecs -nodes=4 $@
echo "SUITE SUCCESS"
)

